--liquibase formatted sql

--changeset Mikhail.Rovsha:1
--comment gamecharacters table initial creation

create table gamecharacters
(
    id           bigint generated by default as identity primary key,
    name         varchar(30) not null,
    "user"       bigint      not null constraint fk_gamecharacters_users_id references users,
    strength     smallint    not null,
    dexterity    smallint    not null,
    constitution smallint    not null,
    intellect    smallint    not null,
    wisdom       smallint    not null,
    charisma     smallint    not null
)