--liquibase formatted sql

--changeset Mikhail.Rovsha:1
--comment users table initial creation

create table session
(
    id                bigint generated by default as identity primary key,
    user_id        bigint      null
        constraint fk_state_tg_user_tg_id references tg_user,
    game_character_id bigint      null
        constraint fk_state_game_character_id references game_character,
    state             varchar(30) not null,
    date_created      timestamp        not null,
    date_expire       timestamp        not null
)